### ISSUE TITLE
How to use Gdash in Gluster container

### ISSUE THREAD

**Issue by zzzhangqi** [kadalu/gdash#29]
Hello，How to use Gdash in Gluster container

Please give me some guidance Thank you

**Comment by aravindavk** [comment]
Run in any one of server node and then access from outside. For example, if gdash is running in node1.example.com then access that using http://node1.example.com:8080

**Comment by aravindavk** [comment]
I read updated title now. How are you running gluster inside container? Are you using systemd based container image?

**Comment by zzzhangqi** [comment]
Yes, it is a systemd GlusterFS container. I am currently running in Kubernetes. How do I run Gdash with a separate pod

**Comment by zzzhangqi** [comment]
I tried to package the Python-based Gdash image and run it as a pod in Kubernetes. I found that I cannot access the GlusterFS cluster. How should I configure it

**Comment by aravindavk** [comment]
> I tried to package the Python-based Gdash image and run it as a pod in Kubernetes. I found that I cannot access the GlusterFS cluster. How should I configure it

Since Gdash is running gluster CLI, it is not possible to start in external Pod right now.

If possible you can rebuild the server container images and include gdash as systemd service.

Example systemd unit file

```
[Unit]
Description=Gdash
After=network.target

[Service]
PIDFile=/var/run/gdash/server.pid
ExecStart=/usr/bin/gdash node1.example.com --auth-file=/etc/gdash/gdash.dat

[Install]
WantedBy=multi-user.target
```

Auth file can be mounted using Configmap or secret so that it will be available as `/etc/gdash` in all server nodes.

**Comment by zzzhangqi** [comment]
If don't pip install gdash, are there any other ways to install it?
