### ISSUE TITLE
[Bug] Unable to see Volume Details after updates to React Router

### ISSUE THREAD

**Issue by gaby** [kadalu/gdash#64]
@aravindavk The recent update of dependencies seem to have broken several pages. The issue is mostly caused by the upgrade to React Router from v5 to v6.

For example clicking on a volume doesnt show the details anymore. 

More info here: https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6

**Comment by aravindavk** [comment]
Thanks for the pointers. Will fix the issue and trigger new release today.

**Comment by gaby** [comment]
@aravindavk Latest version fixed the issue with the volume details page. I also noticed the 3 boxes in the dashboard have the same issue. Everything else seems to be working fine so far.

**Comment by aravindavk** [comment]
Cool. I will work on the remaining issues. Thanks.

I would like to know more about the GlusterFS usage in your company or home lab. If possible, please share the details about the GlusterFS use case and the experience with it.

**Comment by gaby** [comment]
@aravindavk Right now it's mostly home lab setup with multiple volumes replicated across 3 nodes.
