### ISSUE TITLE
react-router-dom upgrade issues

### ISSUE THREAD

**Issue by aravindavk** [kadalu/gdash#66]
From Gluster Slack

**Tai Nguyen Huu [2:21 PM](https://gluster.slack.com/archives/CH79R0QKS/p1672131100887539):**

Hi everyone, I have a cluster glusterfs. I have install gdash to manage the cluster.  I installed gdash use  pip3 install gdask  and enable by command gdash [web.glusterfs.com](http://web.glusterfs.com/)  --auth-file a.txt --port 10000. When I connect to dashboard from browser, I get the error GET /api/volumes HTTP/1.1" 403 22 "http://10.84.86.36:10000/volumes" 

**Aravinda (kadalu.tech) [2:50 PM](https://gluster.slack.com/archives/CH79R0QKS/p1672132804488209?thread_ts=1672131100.887539&cid=CH79R0QKS):**

Looks like a new issue while redirecting to login screen. I will look into the issue. As a workaround, can you try http://10.84.86.36:10000/login and then open http://10.84.86.36:10000/

**Comment by aravindavk** [comment]
Similar issue to be fixed in dashboard page: https://github.com/kadalu/gdash/issues/64#issuecomment-1364602153

**Comment by gaby** [comment]
@aravindavk What's the plan to solve this issue?

**Comment by aravindavk** [comment]
Fixed with the release 1.1.3. Please reopen if this issue persists.

**Comment by gaby** [comment]
Thanks!
